# Configuration Options for LaREST

# LOGGING -----------

[logging]
version = 1

[logging.formatters]

[logging.formatters.default]
format = "%(asctime)s:%(name)s:%(levelname)s:%(message)s"

[logging.handlers]

[logging.handlers.file]
class = "logging.FileHandler"
level = "DEBUG"
encoding = "utf-8"
filename = "larest.log"
formatter = "default"
mode = "a"

[logging.handlers.stream]
class = "logging.StreamHandler"
level = "DEBUG"
formatter = "default"

[logging.root]
handlers = ["file", "stream"]
level = "DEBUG" # [DEBUG, INFO]

# REACTION -------------

[reaction]
type = "ROR" # ["RER", "ROR"]
lengths = [1, 2, 3] # list[int]
initiator = "C1=CC=C(C=C1)C(=O)O" # str
monomers = ["O=C1CCO1", "O=C1CCCO1", "O=C1CCCCO1"] # list[str]

[rdkit]
n_cores = 16
n_conformers = 20
random_seed = 42
conformer_box_size = 2.0
precision = 6
mmff = "MMFF94"
mmff_iters = 200
align_iters = 50

[xtb]
[xtb.rdkit]
parallel = 16
ohess = "vtight"
etemp = 298.15
verbose = true
json = true
alpb = "toluene"
gfn = 2
acc = 1.0
iterations = 250

[xtb.crest]
parallel = 16
hess = true
# ohess = "vtight"
# bhess = "vtight"
etemp = 298.15
verbose = true
json = true
alpb = "toluene"
gfn = 2
acc = 1.0
iterations = 250

# ----------------------

[crest]
[crest.confgen]
# general
T = 16
niceprint = true
# runtype
v3 = true
# level of theory
gfn2 = true
alpb = "toluene"
optlev = "vtight"
# molecular dynamics
mdlen = "x1"
shake = 2
tstep = 5
mddump = 100
vbdump = 1
# conformational search
tnmd = 400
mrest = 5
maxflip = 100
keepdir = false
# ensemble sorting (CREGEN)
ewin = 6.0
rthr = 0.125
ethr = 0.05
bthr = 0.01
athr = 0.04
nmr = true
temp = 298.15

[step2.confgen.xtb]
verbose = true
json = true
hess = true
alpb = "toluene"
gfn = 2
# bhess = "vtight"
acc = 1.0
iterations = 250
etemp = 298.15
sthr = 25.0

[step2.xtb.thermo]
# runtype
# thermo = true
# legacy = true
# level of theory
# gfn2 = true
# alpb = "toluene"
# entropy mode settings
# ptot = 0.9
# fscal = 1.0
# sthr = 25.0
# ithr = -50.0

# verbose = true
# json = true
# alpb = "toluene"
# gfn = 2
# bhess = "vtight"
# acc = 1.0
# iterations = 250
# etemp = 298.15
# sthr = 25.0

[step2.censo]

[step2.censo.general]
imagthr = -100.0
sthr = 25.0 # changed to match paper?
scale = 1.0
temperature = 298.15
solvent = "toluene"
sm_rrho = "alpb"
evaluate_rrho = true
consider_sym = true
bhess = true
rmsdbias = false
balance = true
gas-phase = false
copy_mo = true
retry_failed = true

[step2.censo.prescreening]
threshold = 4.0
func = "pbe-d4"
basis = "def2-SV(P)"
prog = "orca"
gfnv = "gfn2"
template = false
run = false

[step2.censo.screening]
threshold = 3.5
func = "r2scan-3c"
basis = "def2-TZVP"
prog = "orca"
sm = "smd"
gfnv = "gfn2"
implicit = true
template = false
run = false

[step2.censo.optimization]
macrocycles = true
optcycles = 8
maxcyc = 200
threshold = 3.0
hlow = 0.01
gradthr = 0.01
func = "r2scan-3c"
basis = "def2-TZVP"
prog = "orca"
sm = "smd"
gfnv = "gfn2"
optlevel = "normal"
template = false
xtb_opt = true
run = true

[step2.censo.refinement]
threshold = 0.95
func = "wb97x-v"
basis = "def2-TZVP"
prog = "orca"
sm = "smd"
gfnv = "gfn2"
implicit = true
template = false
run = false # unnecessary?

[step2.censo.nmr]
resonance_frequency = 300.0
ss_cutoff = 8.0
prog = "orca"
func_j = "pbe0-d4"
basis_j = "def2-tZVP"
sm_j = "smd"
func_s = "pbe0-d4"
basis_s = "def2-tZVP"
sm_s = "smd"
gfnv = "gfn2"
template = false
couplings = true
fc_only = true
shieldings = true
h_active = true
c_active = true
f_active = false
si_active = false
p_active = false
run = false # unnecessary?

[step2.censo.uvvis]
prog = "orca"
func = "wb97x-d4"
basis = "def2-TZVP"
sm = "smd"
gfnv = "gfn2"
nroots = 20
template = false
run = false # unnecessary?

[step2.censo.paths]
orcaversion = "6.1.0"
