# Basic Configuration Options for LaREST

# All settings passed here will be merged with `default.toml`
# In the case of duplicate keys, settings here take precedence

# REACTION -------------

[reaction]
type = "RER" # ["RER", "ROR"]
lengths = [2, 3, 4] # list[int]
initiator = "C1=CC=C(C=C1)CO" # str
monomers = [ # list[str]
    "O=C1OCC1",
    "O=C1OCCC1",
    "O=C1OCCCC1",
]

# STEPS -------------

[steps]
rdkit = true
crest_confgen = true
censo = true
crest_entropy = true
xtb = true # used to rank rdkit and crest_confgen

# RDKIT -------------

[rdkit]
n_cores = 16
n_conformers = 50
random_seed = 42

# xTB -------------

[xtb]
parallel = 16 # int
gfn = 2
# gfnff = true
ohess = "vtight"
alpb = "toluene"

# CREST -------------

[crest]
[crest.confgen]
# general
T = 16
gfn2 = true # or gfnff = true
alpb = "toluene"
optlev = "vtight"
# ensemble sorting (CREGEN)
# requires benchmarking
ewin = 6.0
rthr = 0.125
ethr = 0.05
bthr = 0.01

[crest.entropy]
# general
T = 16
gfnff = true
alpb = "toluene"
optlev = "vtight"
# ensemble sorting (CREGEN)
# requires benchmarking
ewin = 6.0
rthr = 0.125
ethr = 0.05
bthr = 0.01

# CENSO -------------

[censo]
[censo.cli]
maxcores = 8

[censo.general]
solvent = "toluene"
sm_rrho = "alpb"
evaluate_rrho = true

[censo.prescreening]
run = true
threshold = 4.0
func = "pbe-d4"
basis = "def2-SV(P)"
gfnv = "gfn2"

[censo.screening]
run = true
threshold = 3.0
func = "r2scan-3c"
basis = "def2-TZVP"
sm = "smd"
gfnv = "gfn2"

[censo.optimization]
run = true
threshold = 2.0
macrocycles = true
optcycles = 4
maxcyc = 200
gradthr = 0.01
func = "r2scan-3c"
basis = "def2-TZVP"
sm = "smd"
gfnv = "gfn2"

[censo.refinement]
run = true
threshold = 1.0
func = "wb97x-v"
basis = "def2-TZVP"
sm = "smd"
gfnv = "gfn2"

[censo.paths]
orcaversion = "6.1.0" # replace as necessary
