# CREST input options
input = "/data/input/input.txt"
runtype = "ancopt"
threads = 16

[calculation]
elog = "/data/output/crest/energies.log"
eprint = true
optlev = "tight" # crude, vloose, loose, normal, tight, vtight, extreme

[[calculation.level]]
opt_engine = "ancopt"
hess_update = "bfgs"
method = "gfn2"
alpb = "toluene"

[cregen]
ewin = 6.0
rthr = 0.125
ethr = 0.05
bthr = 0.01
nmr = false

ohess_level: vtight              # ['normal', 'tight', 'vtight', 'extreme']
