[logging]
version = 1

[logging.formatters]

[logging.formatters.default]
format = "%(asctime)s:%(name)s:%(levelname)s:%(message)s"

[logging.handlers]

[logging.handlers.file]
class = "logging.FileHandler"
level = "DEBUG"
encoding = "utf-8"
formatter = "default"
mode = "a"

[logging.handlers.stream]
class = "logging.StreamHandler"
level = "DEBUG"
formatter = "default"

[logging.root]
handlers = ["file", "stream"]
level = "DEBUG" # most of the time you're just adjusting this
# ["DEBUG", "INFO"]
