version = 1

[formatters]

[formatters.default]
format = "%(asctime)s:%(name)s:%(levelname)s:%(message)s"

[handlers]

[handlers.file]
class = "logging.FileHandler"
level = "DEBUG"
encoding = "utf-8"
formatter = "default"
mode = "a"

[handlers.stream]
class = "logging.StreamHandler"
level = "INFO"
formatter = "default"

[root]
handlers = ["file", "stream"]
level = "DEBUG" # most of the time you're just adjusting this
# ["DEBUG", "INFO"]
