# Configuration Options for Step 1 (xTB)
title = "Step 1 Config"

[reaction]
type = "ROR"
lengths = [2, 3, 4, 5, 6]

[monomer]
n_conformers = 20

[initiator]
smiles = "C1=CC=C(C=C1)C(=O)O"
n_conformers = 20

[polymer]
n_conformers = 20

[rdkit]
random_seed = 42
conformer_box_size = 2.0
threads = 16
precision = 6
mmff = "MMFF94"
mmff_iters = 200
align_iters = 50

num_repeat = 1
energy_option = 1

[xtb]
ohess = "vtight"
alpb = "Toluene"
gfn = 2
parallel = 16
acc = 1.0
iterations = 250
etemp = 298.15

