[general]
imagthr = -100.0
sthr = 0.0
scale = 1.0
temperature = 298.15
solvent = "toluene"
sm_rrho = "alpb"
evaluate_rrho = true
consider_sym = true
bhess = true
rmsdbias = false
balance = true
gas-phase = false
copy_mo = true
retry_failed = true

[prescreening]
threshold = 4.0
func = "pbe-d4"
basis = "def2-SV(P)"
prog = "orca"
gfnv = "gfn2"
run = true
template = false

[screening]
threshold = 3.5
func = "r2scan-3c"
basis = "def2-TZVP"
prog = "orca"
sm = "cosmors"
gfnv = "gfn2"
run = true
implicit = false
template = false


[censo.optimization]
optcycles = 8
maxcyc = 200
threshold = 3.0
hlow = 0.01
gradthr = 0.01
func = "r2scan-3c"
basis = "def2-TZVP"
prog = "orca"
sm = "dcosmors"
gfnv = "gfn2"
optlevel = "normal" # vtight?
run = true
macrocycles = true
macrocycles = true
template = false
xtb_opt = true

[refinement]
threshold = 0.95
func = "wb97x-v"
basis = "def2-TZVP"
prog = "orca"
sm = "cosmors"
gfnv = "gfn2"
run = true
implicit = false
template = false

[nmr]
resonance_frequency = 300.0
ss_cutoff = 8.0
prog = "orca"
func_j = "pbe0-d4"
basis_j = "def2-tZVP"
sm_j = "smd"
func_s = "pbe0-d4"
basis_s = "def2-tZVP"
sm_s = "smd"
gfnv = "gfn2"
run = false
template = false
couplings = true
fc_only = true
shieldings = true
h_active = true
c_active = true
f_active = false
si_active = false
p_active = false

[uvvis]
prog = orca
func = wb97x-d4
basis = def2-TZVP
sm = smd
gfnv = gfn2
nroots = 20
run = False
template = False
