# Configuration Options for Step 1 (xTB)
title = "Step 1 Config"
N_CORES = 16

[reaction]
type = "ROR" # ["RER", "ROR"]
lengths = [1, 2, 3, 4]

[monomer]
n_conformers = 20

[initiator]
smiles = "C1=CC=C(C=C1)C(=O)O"
n_conformers = 20

[polymer]
n_conformers = 20

[rdkit]
random_seed = 42
conformer_box_size = 2.0
threads = 16 # TODO: this has to be adjustable with N_CORES
precision = 6
mmff = "MMFF94"
mmff_iters = 200
align_iters = 50

[xtb]
verbose = true
json = true
ohess = "vtight"
alpb = "toluene"
gfn = 2
parallel = 16 # TODO: this too
acc = 1.0
iterations = 250
etemp = 298.15

[crest]
# general
T = 16
niceprint = true
# runtype
v3 = true
# level of theory
gfn2 = true
alpb = "toluene"
optlev = "vtight"
# molecular dynamics
mdlen = "x1"
shake = 2
tstep = 5
mddump = 100
vbdump = 1
# conformational search
tnmd = 400
mrest = 5
maxflip = 100
keepdir = false
# ensemble sorting (CREGEN)
ewin = 6.0
rthr = 0.125
ethr = 0.05
bthr = 0.01
athr = 0.04
nmr = true
temp = 298.15

